apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: nginx
data:
 index.html: |
   <html>
   <head><title>Hello from Argo now amen</title></head>
   <body>
   <h1>Hello from Argo</h1>
   </body>
   </html>